Added touch events
markuszeller/image-stitcher pull request #35
Opened 2024-04-16 05:25 UTC by vschwaberow

Should be fixing the iOS / Android functionality.

2024-04-16 16:43 UTC, markuszeller requested changes

2024-04-16 16:43 UTC, markuszeller commented on app/js/main.js
> +document.addEventListener(TOUCH_START_EVENT, handleTouchStart);
Funktioniert das ohne die Methoden handleTouch* oder sind die Bestandteil vom Safari?

2024-04-17 02:51 UTC, vschwaberow commented on app/js/main.js
> +document.addEventListener(TOUCH_START_EVENT, handleTouchStart);
Natürlich vergessen. Danke.

2024-04-17 08:36 UTC, markuszeller requested changes

2024-04-17 08:36 UTC, markuszeller commented on app/js/main.js
> +function getTouchTargetElement(e) {
Best Practice ist es, nicht Funktionen direkt zu deklarieren, weil sie dem global Namespace zugeordnet werden. Besser ist:

`const getTouchTargetElement = (e) => { ... };`

So ist sie nur lokal vorhanden und durch den fn short Syntax steht der gesamte lexikalische Scope (inkl. "this") zur Verfügung.

Nachteil ist hier, dass kein Hoisting mehr geht, aber man kann die const vor der Nutzung deklarieren.

2024-04-17 08:36 UTC, markuszeller commented on app/js/main.js
> +    if (!dragState) return;
Codestyle:

```
if (!dragState) {
    return;
}
```

2024-04-17 08:36 UTC, markuszeller commented on app/js/main.js
> +    if (sourceRect.top > targetRect.top) {
Else, falls möglich vermeiden.

```
    if (sourceRect.top > targetRect.top) {
        targetElement.before(dragSource);

        return;
    }

    targetElement.after(dragSource);
```

2024-04-17 08:36 UTC, markuszeller commented on app/js/main.js
> +    if (!dragState) return;
Codestyle: Bitte immer Codeblock.

2024-04-17 08:36 UTC, markuszeller commented on app/js/main.js
> +    return document.elementFromPoint(touch.clientX, touch.clientY);
Codestyle: Bitte vor jedem `return` eine Leerzeile.

2024-04-19 09:53 UTC, markuszeller approved these changes
Vielen Dank!

2024-04-19 09:54 UTC, merged